openapi: 3.1.0
info:
  version: 1.0.0
  title: My Contacts Book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation of my contacts book backend
tags:
  - name: Contacts
    description: All the operations with your contacts
  - name: Contact
    description: All the operations with the particular contact (by ID)
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-7-in4s.onrender.com
paths:
  /contacts/{contactId}:
    get:
      $ref: ../swagger/path/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/path/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/path/contacts/{id}/delete.yaml
  /contacts:
    get:
      $ref: ../swagger/path/contacts/get.yaml
    post:
      $ref: ../swagger/path/contacts/post.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
