openapi: 3.1.0
info:
  version: 1.0.0
  title: My Contacts Book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation of my contacts book
tags:
  - name: Contacts
    description: My Contacts Book
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-7-in4s.onrender.com
paths: /contacts/:contactId:
  get:
    $ref: ../swagger/student/{id}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
